import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "ghostwhite",
  },
  goalButton: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "mediumseagreen",
    marginBottom: 10,
    borderRadius: 100,
  },
  academicButton: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "royalblue",
    marginBottom: 10,
    borderRadius: 100,
  },
  fitnessButton: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "tomato",
    marginBottom: 10,
    borderRadius: 100,
  },
  financeButton: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "goldenrod",
    marginBottom: 10,
    borderRadius: 100,
  },
});
