import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flexDirection: "row",
    justifyContent: "center",
    height: "auto",
    width: "auto",
    marginTop: 25,
  },
  goalListContainer: {
    height: "auto",
    width: 350,
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "mediumseagreen",
  },
  academicListContainer: {
    height: "auto",
    width: 350,
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "royalblue",
  },
  fitnessListContainer: {
    height: "auto",
    width: 350,
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "tomato",
  },
  financeListContainer: {
    height: "auto",
    width: 350,
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "goldenrod",
  },
  circleContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 10,
  },
  checkContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 10,
  },
  listText: {
    color: "ghostwhite",
    width: 260,
    height: "auto",
    fontSize: 20,
    marginTop: 5,
    marginRight: 10,
  },
  listSubtext: {
    color: "black",
    fontSize: 12,
    marginRight: 20,
    borderRadius: 10,
    width: 200,
  },
  iconContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 15,
    marginBottom: 5,
    height: 40,
    borderRadius: 10,
  },
});
